name: Deploy Infrastructure

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: "Terraform"
    runs on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
      TF_VAR_env_name: prod

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: "Terraform init"
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_subcommand: "init"
          tf_actions_working_dir: "./infra"
          tf_actions_version: 1.3.7

      - name: "Terraform apply"
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_subcommand: "apply"
          tf_actions_working_dir: "./infra"
          tf_actions_version: 1.3.7